services:
  catalogapi:
     build:
        context: ./src/Services/Catalog/EShop.Service.CatalogAPI
        dockerfile: Dockerfile
     environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - ASPNETCORE_HTTP_PORTS=8080
     ports:
        - "6000:8080"
     depends_on:
        - catalogdb
     volumes:
        - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
        - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  basketgapi:
     build:
        context: ./src/Services/Basket/EShop.Service.BasketAPI
        dockerfile: Dockerfile
     environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - ASPNETCORE_HTTP_PORTS=8080
        - GrpcSettings__DiscountUrl=http://discountgrpc:8080
     ports:
        - "6001:8080"
     depends_on:
        - basketdb
     volumes:
        - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
        - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro 

  discountgrpc:
     build:
        context: ./src/Services/Discount/EShop.Service.DiscountGRPC
        dockerfile: Dockerfile
     environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - ASPNETCORE_HTTP_PORTS=8080
        - ConnectionStrings__Database=Data Source=discountdb
     ports:
        - "6002:8080"
     volumes:
        - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
        - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  distributedcache:
     container_name: distributedcache
     restart: always
     ports:
        - "6379:6379"

  catalogdb:
     container_name: catalogdb
     environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=123456
        - POSTGRES_DB=EShopCatalogDb
     restart: always
     ports:
        - "5433:5432"
     volumes:
        - postgres_catalog:/var/lib/postgresql/data/  

  basketdb:
     container_name: basketdb
     environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=123456
        - POSTGRES_DB=EShopBasketDb
     restart: always
     ports:
        - "5432:5432"
     volumes:
        - postgres_basket:/var/lib/postgresql/data/  